eureka:
    client:
        enabled: false

spring:
    cloud:
        discovery:
            enabled: false

    # 만약 MongoDB 관련 에러가 발생한다면 아래 설정을 추가
    # data:
    #   mongodb:
    #     uri: mongodb://localhost:27017/test
