spring:
    application:
        name: catalog-service
    profiles:
        active: local

server:
    port: 19800

catalog:
    kafka:
        topic:
            product-created: "product.created"
            stock-reserved: "stock.reserved"
            stock-restored: "stock.restored"
