spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/michelet_catalog
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: catalog-service-consumer
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "com.michelet.catalog"

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
