### 환경 변수 설정
@host = localhost
@gatewayPort = 19000
@catalogPort = 19800

### 1. [Public] 상품 전체 조회 (목록)
GET http://{{host}}:{{gatewayPort}}/api/v1/products?page=0&size=10
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("전체 조회 성공", function () {
        client.assert(response.status === 200, "조회 실패");
        client.assert(response.body.content !== undefined, "데이터가 없습니다.");
    });
%}

### 2. [Public] 상품 상세 조회 (단건)
# inventory.http에서 상품 등록 후 넘어온 shared_product_id 사용
GET http://{{host}}:{{gatewayPort}}/api/v1/products/{{shared_product_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("상세 조회 및 카프카 데이터 동기화 확인", function () {
        client.assert(response.status === 200, "상세 조회 실패");
        client.assert(response.body.productId === client.global.get("shared_product_id"), "ID 불일치(동기화 실패)");
    });
%}

### 3. [Internal] 옵션 검증 단건 유효성 및 가격 검증 API
GET http://{{host}}:{{catalogPort}}/internal/options/{{shared_option_id}}/validate
Accept: application/json
X-User-Role: SYSTEM

> {%
    client.test("옵션 검증 및 가격 합산 로직 확인", function () {
        client.assert(response.status === 200, "옵션 검증 API 호출 실패");

        // basePrice와 addPrice가 합산된 totalPrice가 200,000인지 확인
        client.assert(response.body.data.totalPrice === 200000, "가격 합산 오류: " + response.body.data.totalPrice);
        client.log("최종 계산된 결제 가격: " + response.body.data.totalPrice);
    });
%}
